---

checks:
  - name: "ya.ru"
    host: "ya.ru"
    url: "https://ya.ru/"
    status_code: 200
    load_time: 2
    min_ssl_expiry_days: 30
    ssl_subject: "yandex.ru"
    search: "yandex"

telegram:
  tuserid: "TelegramUserId, use @myidbot"
  ttoken: 'Toker for your Telegram Bot'
