name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-out repo
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python3 -m pip install -r ./requirements.txt

      - name: Run
        run: |
          ./kmon.py -c ./config.example.yaml run

  linter_test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout-out repo
        uses: actions/checkout@v2

      - name: Install requirements for test
        run: |
          python3 -m pip install flake8
